name: "Build astro site"
description: "Builds astro site."

runs:
  using: "composite"
  steps:
    - name: Checkout your repository using git
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'pnpm'
    - run: pnpm install
      shell: bash