name: Run checks

on: [ push]
 
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Build environment
        uses: ./.github/actions/build-astro

      - run: pnpm check