name: Run checks

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Build environment
        uses: oven-sh/setup-bun@v1

      - run: bun check
